name: CI
on:
  pull_request:
    types:
      - labeled
    branches: [ main ]

jobs:
  check-repo-activity-for-pr:
    if: github.event.label.name == 'contribution_to_opensource'
    runs-on: ubuntu-latest
    name: PR activity check
    steps:
    - name: Run index
      id: index
      uses: sfkwww/milkyway@v0.5
      with:
        github_token: ${{ secrets.TOKEN }}
        pr_body: ${{ github.event.pull_request.body }}
        min_stars: 10
        min_watchers: 10
        min_contributors: 10
        min_forks: 1
        min_commits: 100
        min_commits_last_year: 10
        min_open_issues: 10
    - name: Echo
      run: echo '${{ steps.index.outputs.stars }}'
    - name: Comment the results
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.TOKEN}}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `
            [ ${{steps.index.outputs.repo}} ]
            -----------------------
            - Stars ⭐: ${{steps.index.outputs.stars.count}} ${{ fromJSON('["❌", "✔️"]')[steps.index.outputs.stars.pass] }}
            `
          })
