name: CI
on:
  pull_request:
    types:
      - labeled
    branches: [ main ]

jobs:
  check-repo-activity-for-pr:
    if: github.event.label.name == 'contribution_to_opensource'
    runs-on: ubuntu-latest
    name: PR activity check
    steps:
    - name: Run index
      id: index
      uses: actions/milkyway@*
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_body: ${{ github.event.pull_request.body }}
        pr_title: ${{ github.event.pull_request.title }}
        pr_id: ${{ github.event.pull_request.number }}
        repo: ${{ github.repository }}
    - name: Get the output
      run: echo "The Repo was ${{ steps.index.outputs.repo }}"
